---
title: "maps"
author: "Hamid Khan"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, include=F}

library(tidyverse)

library("tidycensus")

census_api_key("d080928bdb02fba2a577dc87f6db96de381c60cd")

```

```{r maps, include=F}

racevars <- c(White = "B02001_002", 
              
              Black = "B02001_003", 
              
              Asian = "B02001_005",
              
              Hispanic = "B03003_003")

harris <- get_acs(geography = "tract",
                  
                  variables = racevars, 
                  
                  year = 2018,
                  
                  state = "MA",
                  
                  county = "Middlesex County",
                  
                  geometry = TRUE,
                  
                  summary_var = "B02001_001") 

harris %>%
  
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  
  ggplot(aes(fill = Percent, color = Percent)) +
  
  facet_wrap(~ variable) +
  
  geom_sf() +
  
  scale_fill_viridis_c(direction = -1) +
  
  scale_color_viridis_c(direction = -1) +
  
  labs(title = "Racial geography of Middlesex County, MA",
       
  caption = "Source: American Community Survey 2014-2018") +
  
  theme_void()

```

`r harris`